#!/bin/bash
# Quick commands for parallel FL experiments

echo "════════════════════════════════════════════════"
echo "  FL M3 Parallel Experiments - Quick Reference  "
echo "════════════════════════════════════════════════"
echo ""
echo "📋 SETUP:"
echo "  docker-compose -f docker-compose-parallel.yml up -d"
echo ""
echo "🚀 RUN 3 EXPERIMENTS IN PARALLEL:"
echo "  bash run_parallel_experiments.sh"
echo ""
echo "📊 MONITOR:"
echo "  docker logs -f fl_lstm_exp1_server  # Experiment 1"
echo "  docker logs -f fl_lstm_exp2_server  # Experiment 2"
echo "  docker logs -f fl_lstm_exp3_server  # Experiment 3"
echo ""
echo "🔍 CHECK STATUS:"
echo "  docker ps | grep fl_lstm_exp"
echo ""
echo "🛑 STOP:"
echo "  docker-compose -f docker-compose-parallel.yml down"
echo ""
echo "🧹 CLEANUP:"
echo "  docker-compose -f docker-compose-parallel.yml down -v"
echo "  docker system prune -a"
echo ""
echo "════════════════════════════════════════════════"
echo ""
echo "📈 CURRENT SETUP:"
echo "  • 3 parallel experiments (each: 1 server + 5 clients)"
echo "  • 18 total containers"
echo "  • Reduced parameters (3 alphas, key values only)"
echo "  • ~2 hours total execution time"
echo "  • 30-50x faster than original"
echo ""
echo "💡 RESOURCES NEEDED:"
echo "  • CPU: 36+ cores"
echo "  • RAM: 72+ GB"
echo "  • GPU: 2-4 GPUs"
echo ""
echo "════════════════════════════════════════════════"
