#!/bin/bash
# Quick Start Guide for FL_IoT_Network Experiments

echo "======================================"
echo "FL_IoT_Network - Quick Start Guide"
echo "======================================"
echo ""

# Step 1: Check data files
echo "Step 1: Checking data files..."
if [ -d "fl_testbed/version2/data/transformed" ]; then
    PKL_COUNT=$(ls fl_testbed/version2/data/transformed/*.pkl 2>/dev/null | wc -l)
    echo "✓ Data directory exists"
    echo "  Files found: $PKL_COUNT pickle files"
    if [ "$PKL_COUNT" -eq 0 ]; then
        echo "  ⚠ WARNING: No data files found! You need to generate them first."
        echo "  Run data preprocessing scripts in fl_testbed/version2/data/initial/"
    fi
else
    echo "✗ Data directory missing!"
    echo "  You need to create: fl_testbed/version2/data/transformed/"
    exit 1
fi

# Step 2: Update IP addresses in scripts (OLD: 172.17.0.x -> NEW: 172.18.0.x)
echo ""
echo "Step 2: Updating IP addresses in execution scripts..."
echo "  Changing 172.17.0.x to 172.18.0.x..."

# Update all execution scripts
find . -name "*execution*.sh" -type f -exec sed -i 's/172\.17\.0\./172.18.0./g' {} \;
echo "✓ IP addresses updated in all execution scripts"

# Step 3: Verify containers
echo ""
echo "Step 3: Checking Docker containers..."
docker compose ps | grep -q "Up" && echo "✓ Containers are running" || (echo "✗ Containers not running! Run: docker compose up -d" && exit 1)

# Step 4: Show how to run
echo ""
echo "======================================"
echo "HOW TO RUN EXPERIMENTS"
echo "======================================"
echo ""
echo "METHOD 1: Manual (Best for debugging)"
echo "--------------------------------------"
echo ""
echo "Terminal 1 (Server):"
echo "  docker exec -it fl_server bash"
echo "  cd /workspace"
echo "  ./server_execution_LSTM_M1.sh    # For LSTM/RUL experiments"
echo "  # OR"
echo "  ./server_execution_MLP_M1.sh     # For MLP/OFFSET experiments"
echo ""
echo "Terminal 2-6 (5 Clients in parallel):"
echo "  docker exec -it fl_client1 bash"
echo "  cd /workspace"
echo "  ./client1_execution_LSTM_M1.sh   # Run this in client1"
echo ""
echo "  # Repeat for clients 2-5 with their respective scripts"
echo "  # client2_execution_LSTM_M1.sh in fl_client2"
echo "  # client3_execution_LSTM_M1.sh in fl_client3"
echo "  # etc..."
echo ""
echo "METHOD 2: Background execution"
echo "--------------------------------------"
echo ""
echo "# Start server in background"
echo "docker exec -d fl_server bash -c 'cd /workspace && ./server_execution_LSTM_M1.sh'"
echo ""
echo "# Wait 10 seconds for server to initialize"
echo "sleep 10"
echo ""
echo "# Start all clients in background"
echo "for i in {1..5}; do"
echo "  docker exec -d fl_client\${i} bash -c 'cd /workspace && ./client\${i}_execution_LSTM_M1.sh'"
echo "done"
echo ""
echo "# Monitor logs"
echo "docker logs -f fl_server"
echo ""
echo "======================================"
echo "AVAILABLE EXPERIMENTS"
echo "======================================"
echo ""
echo "LSTM (RUL Prediction):"
echo "  - server_execution_LSTM_M1.sh  (Motor 1)"
echo "  - server_execution_LSTM_M2.sh  (Motor 2)"
echo "  - server_execution_LSTM_M3.sh  (Motor 3)"
echo "  - server_execution_LSTM_M3_ALPHA.sh  (Alpha parameter sweep)"
echo "  - server_execution_LSTM_M3_NEW_METHODS.sh  (MOON & FedALA)"
echo ""
echo "MLP (OFFSET Prediction):"
echo "  - server_execution_MLP_M1.sh   (Motor 1)"
echo "  - server_execution_MLP_M2.sh   (Motor 2)"
echo "  - server_execution_MLP_M3.sh   (Motor 3)"
echo "  - server_execution_MLP_M3_ALPHA.sh  (Alpha parameter sweep)"
echo "  - server_execution_MLP_M3_NEW_METHODS.sh  (MOON & FedALA)"
echo ""
echo "======================================"
echo "RESULTS LOCATION"
echo "======================================"
echo ""
echo "Results are saved to /workspace (shared volume):"
echo "  - Output logs: LSTM_*.txt, MLP_*.txt"
echo "  - Models: fl_testbed/version2/data/transformed/*.pkl"
echo "  - You can access them from your host machine at:"
echo "    /home/jose/FL_IoT_Network/"
echo ""
echo "======================================"
echo "USEFUL COMMANDS"
echo "======================================"
echo ""
echo "# View running containers"
echo "docker compose ps"
echo ""
echo "# View server logs"
echo "docker logs -f fl_server"
echo ""
echo "# View client logs"
echo "docker logs -f fl_client1"
echo ""
echo "# Stop all containers"
echo "docker compose down"
echo ""
echo "# Restart containers"
echo "docker compose restart"
echo ""
echo "# Clean up everything"
echo "docker compose down -v"
echo ""
